/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/ai/a basic understanding of ai music': RouteRecordInfo<'/posts/ai/a basic understanding of ai music', '/posts/ai/a basic understanding of ai music', Record<never, never>, Record<never, never>>,
    '/posts/ai/chance of ai music': RouteRecordInfo<'/posts/ai/chance of ai music', '/posts/ai/chance of ai music', Record<never, never>, Record<never, never>>,
    '/posts/career planning/career essay/local life': RouteRecordInfo<'/posts/career planning/career essay/local life', '/posts/career planning/career essay/local life', Record<never, never>, Record<never, never>>,
    '/posts/career planning/career essay/Should I choose a large company or a small company': RouteRecordInfo<'/posts/career planning/career essay/Should I choose a large company or a small company', '/posts/career planning/career essay/Should I choose a large company or a small company', Record<never, never>, Record<never, never>>,
    '/posts/career planning/industry essay/product manager': RouteRecordInfo<'/posts/career planning/industry essay/product manager', '/posts/career planning/industry essay/product manager', Record<never, never>, Record<never, never>>,
    '/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer': RouteRecordInfo<'/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer', '/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer', Record<never, never>, Record<never, never>>,
    '/posts/career planning/plannning/suggestions of looking for a computer job copy': RouteRecordInfo<'/posts/career planning/plannning/suggestions of looking for a computer job copy', '/posts/career planning/plannning/suggestions of looking for a computer job copy', Record<never, never>, Record<never, never>>,
    '/posts/career planning/plannning/What would my ideal life look like': RouteRecordInfo<'/posts/career planning/plannning/What would my ideal life look like', '/posts/career planning/plannning/What would my ideal life look like', Record<never, never>, Record<never, never>>,
    '/posts/guitar/fender america': RouteRecordInfo<'/posts/guitar/fender america', '/posts/guitar/fender america', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/interview notes/20231120-behavioral-interview-notes': RouteRecordInfo<'/posts/interview notes/20231120-behavioral-interview-notes', '/posts/interview notes/20231120-behavioral-interview-notes', Record<never, never>, Record<never, never>>,
    '/posts/personal summary/24th-birthday-summary': RouteRecordInfo<'/posts/personal summary/24th-birthday-summary', '/posts/personal summary/24th-birthday-summary', Record<never, never>, Record<never, never>>,
    '/posts/personal summary/write for wangdao': RouteRecordInfo<'/posts/personal summary/write for wangdao', '/posts/personal summary/write for wangdao', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/负向治理': RouteRecordInfo<'/posts/study notes/搜推广项目/负向治理', '/posts/study notes/搜推广项目/负向治理', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/广告': RouteRecordInfo<'/posts/study notes/搜推广项目/广告', '/posts/study notes/搜推广项目/广告', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/离线odps任务': RouteRecordInfo<'/posts/study notes/搜推广项目/离线odps任务', '/posts/study notes/搜推广项目/离线odps任务', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/平台化': RouteRecordInfo<'/posts/study notes/搜推广项目/平台化', '/posts/study notes/搜推广项目/平台化', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/搜索工程架构': RouteRecordInfo<'/posts/study notes/搜推广项目/搜索工程架构', '/posts/study notes/搜推广项目/搜索工程架构', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/推荐工程架构': RouteRecordInfo<'/posts/study notes/搜推广项目/推荐工程架构', '/posts/study notes/搜推广项目/推荐工程架构', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/稳定性': RouteRecordInfo<'/posts/study notes/搜推广项目/稳定性', '/posts/study notes/搜推广项目/稳定性', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/在线igraph': RouteRecordInfo<'/posts/study notes/搜推广项目/在线igraph', '/posts/study notes/搜推广项目/在线igraph', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/flink任务': RouteRecordInfo<'/posts/study notes/搜推广项目/flink任务', '/posts/study notes/搜推广项目/flink任务', Record<never, never>, Record<never, never>>,
    '/posts/study notes/搜推广项目/serverless平台': RouteRecordInfo<'/posts/study notes/搜推广项目/serverless平台', '/posts/study notes/搜推广项目/serverless平台', Record<never, never>, Record<never, never>>,
    '/posts/study notes/行为面试题/行为面试': RouteRecordInfo<'/posts/study notes/行为面试题/行为面试', '/posts/study notes/行为面试题/行为面试', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/分布式': RouteRecordInfo<'/posts/study notes/java base knowledge/分布式', '/posts/study notes/java base knowledge/分布式', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/计算机网络': RouteRecordInfo<'/posts/study notes/java base knowledge/计算机网络', '/posts/study notes/java base knowledge/计算机网络', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/设计模式': RouteRecordInfo<'/posts/study notes/java base knowledge/设计模式', '/posts/study notes/java base knowledge/设计模式', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/docker': RouteRecordInfo<'/posts/study notes/java base knowledge/docker', '/posts/study notes/java base knowledge/docker', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/java 异常': RouteRecordInfo<'/posts/study notes/java base knowledge/java 异常', '/posts/study notes/java base knowledge/java 异常', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/java basic knowledge copy': RouteRecordInfo<'/posts/study notes/java base knowledge/java basic knowledge copy', '/posts/study notes/java base knowledge/java basic knowledge copy', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/java io': RouteRecordInfo<'/posts/study notes/java base knowledge/java io', '/posts/study notes/java base knowledge/java io', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/java jvm': RouteRecordInfo<'/posts/study notes/java base knowledge/java jvm', '/posts/study notes/java base knowledge/java jvm', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/mq': RouteRecordInfo<'/posts/study notes/java base knowledge/mq', '/posts/study notes/java base knowledge/mq', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/mysql': RouteRecordInfo<'/posts/study notes/java base knowledge/mysql', '/posts/study notes/java base knowledge/mysql', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/redis': RouteRecordInfo<'/posts/study notes/java base knowledge/redis', '/posts/study notes/java base knowledge/redis', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/rpc': RouteRecordInfo<'/posts/study notes/java base knowledge/rpc', '/posts/study notes/java base knowledge/rpc', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/spring': RouteRecordInfo<'/posts/study notes/java base knowledge/spring', '/posts/study notes/java base knowledge/spring', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/tomcat': RouteRecordInfo<'/posts/study notes/java base knowledge/tomcat', '/posts/study notes/java base knowledge/tomcat', Record<never, never>, Record<never, never>>,
    '/posts/study notes/web3/交易所情况': RouteRecordInfo<'/posts/study notes/web3/交易所情况', '/posts/study notes/web3/交易所情况', Record<never, never>, Record<never, never>>,
    '/posts/we media/why do we media': RouteRecordInfo<'/posts/we media/why do we media', '/posts/we media/why do we media', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
