/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/beining-test1': RouteRecordInfo<'/posts/beining-test1', '/posts/beining-test1', Record<never, never>, Record<never, never>>,
    '/posts/career planning/career essay/local life': RouteRecordInfo<'/posts/career planning/career essay/local life', '/posts/career planning/career essay/local life', Record<never, never>, Record<never, never>>,
    '/posts/career planning/industry essay/product manager': RouteRecordInfo<'/posts/career planning/industry essay/product manager', '/posts/career planning/industry essay/product manager', Record<never, never>, Record<never, never>>,
    '/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer': RouteRecordInfo<'/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer', '/posts/career planning/industry essay/Quantitative Financial Algorithm Engineer', Record<never, never>, Record<never, never>>,
    '/posts/career planning/plannning/suggestions of looking for a computer job': RouteRecordInfo<'/posts/career planning/plannning/suggestions of looking for a computer job', '/posts/career planning/plannning/suggestions of looking for a computer job', Record<never, never>, Record<never, never>>,
    '/posts/guitar/fender america': RouteRecordInfo<'/posts/guitar/fender america', '/posts/guitar/fender america', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/interview notes/20231120-behavioral-interview-notes': RouteRecordInfo<'/posts/interview notes/20231120-behavioral-interview-notes', '/posts/interview notes/20231120-behavioral-interview-notes', Record<never, never>, Record<never, never>>,
    '/posts/personal summary/24th-birthday-summary': RouteRecordInfo<'/posts/personal summary/24th-birthday-summary', '/posts/personal summary/24th-birthday-summary', Record<never, never>, Record<never, never>>,
    '/posts/personal summary/write for wangdao': RouteRecordInfo<'/posts/personal summary/write for wangdao', '/posts/personal summary/write for wangdao', Record<never, never>, Record<never, never>>,
    '/posts/study notes/java base knowledge/java1': RouteRecordInfo<'/posts/study notes/java base knowledge/java1', '/posts/study notes/java base knowledge/java1', Record<never, never>, Record<never, never>>,
    '/posts/we media/why do we media': RouteRecordInfo<'/posts/we media/why do we media', '/posts/we media/why do we media', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
